<?php
// module/Album/view/album/album/index.phtml:

$title = 'Games';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<ul>
<?php
foreach($games_pending as $game){

    // GET THE PLAYERS ATTACHED TO THIS GAME
    $players = $game->getPlayers();
    foreach($players as $player){
        echo "<p>{$player->getId()}</p>";
        $user = $player->getUser();
        echo "<p>".$user->getUserName()."</p>";
    }


}
?>
</ul>

